Refactor GitHub Actions workflow for Docker build

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -1,61 +1,56 @@
 name: Build Image
 
-on:
-  release:
-    types: [published]
-  push:
+on: [push, pull_request, workflow_dispatch]
 
 env:
-  IMAGE: "tailscale-mod"
-  USER: "simcity"
+  ENDPOINT: "simcity/docker-tailscale-mod"
+  BRANCH: "master"
 
 jobs:
   build:
-    name: Build
     runs-on: ubuntu-latest
     steps:
-      - name: Set current date as env variable
-        id: build-time
-        run: echo "NOW=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
+      - uses: actions/checkout@v2.3.3
 
-      - name: Login to Github Container Repo
-        uses: docker/login-action@v3.0.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build image
+        run: |
+          docker build --no-cache -t ${{ github.sha }} .
+      - name: Tag image
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          docker tag ${{ github.sha }} ${ENDPOINT}
+          docker tag ${{ github.sha }} ${ENDPOINT}:${{ github.sha }}
+          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}
+          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}
+      - name: Credential check
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          echo "CR_USER=${{ secrets.CR_USER }}" >> $GITHUB_ENV
+          echo "CR_PAT=${{ secrets.CR_PAT }}" >> $GITHUB_ENV
+          echo "DOCKERUSER=${{ secrets.DOCKERUSER }}" >> $GITHUB_ENV
+          echo "DOCKERPASS=${{ secrets.DOCKERPASS }}" >> $GITHUB_ENV
+          if [[ "${{ secrets.CR_USER }}" == "" && "${{ secrets.CR_PAT }}" == "" && "${{ secrets.DOCKERUSER }}" == "" && "${{ secrets.DOCKERPASS }}" == "" ]]; then
+            echo "::error::Push credential secrets missing."
+            echo "::error::You must set either CR_USER & CR_PAT or DOCKERUSER & DOCKERPASS as secrets in your repo settings."
+            echo "::error::See https://github.com/linuxserver/docker-mods/blob/master/README.md for more information/instructions."
+            exit 1
+          fi
+      - name: Login to GitHub Container Registry
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.CR_USER && env.CR_PAT && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
+      - name: Push tags to GitHub Container Registry
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.CR_USER && env.CR_PAT && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
+          docker push ghcr.io/${ENDPOINT}
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5.0.0
-        with:
-          # list of Docker images to use as base name for tags
-          images: |
-              ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}            
-          # generate Docker tags based on the following events/attributes
-          flavor: 
-            latest=true
-          tags: |
-            type=sha,prefix=,suffix=-${{ github.ref_name }}
-            type=semver,pattern=v{{version}}
-            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
-            type=semver,pattern=v{{major}}.{{minor}}
-          labels: |
-            org.opencontainers.image.created=${{ steps.build-time.outputs.NOW }}
-            org.opencontainers.image.authors=SimCity
-            org.opencontainers.image.url=https://github.com/${{ env.USER }}/docker-mod/packages
-            org.opencontainers.image.source=https://github.com/simcity/docker-mod
-            org.opencontainers.image.version=${{ github.ref_name }}
-            org.opencontainers.image.revision=${{ github.sha }}
-            org.opencontainers.image.vendor=SimCity
-            org.opencontainers.image.licenses=GPL-3.0-only
-            org.opencontainers.image.ref.name=${{ github.sha }}
-            org.opencontainers.image.title=${{ env.IMAGE }}  
-
-      - name: Build and push
-        uses: docker/build-push-action@v5.0.0
-        with:
-          push: ${{ github.event_name == 'release' }}
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          pull: true
+      - name: Login to DockerHub
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.DOCKERUSER && env.DOCKERPASS && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
+      - name: Push tags to DockerHub
+        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.DOCKERUSER && env.DOCKERPASS && env.ENDPOINT != 'user/endpoint' }}
+        run: |
+          docker push ${ENDPOINT}:${{ github.sha }}
+          docker push ${ENDPOINT}
